In [1]:
import helper_functions as hf
import pandas as pd
import numpy as np

In [2]:
df = hf.import_csv_data("processed_data_cardiac_arrest/FACTPCRMEDICATION_CA.csv")
df[:]

/home/ng.chu/nemsis_project/helper_functions.py:19: DtypeWarning: Columns (4,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filepath)

,eMedications_01,PcrMedicationKey,PcrKey,eMedications_03,eMedications_03Descr,eMedications_05,eMedications_06,eMedications_07,eMedications_10,eMedications_02
0,01JAN2020:02:07:55,111612316,71122461,317361,EPINEPHrine 0.1 MG/ML ...,1.0,3706021,9916001,9905007,9923001
1,01JAN2020:02:10:55,111612317,71122461,317361,EPINEPHrine 0.1 MG/ML ...,1.0,3706021,9916001,9905007,9923001
2,01JAN2020:02:13:55,111612318,71122461,317361,EPINEPHrine 0.1 MG/ML ...,1.0,3706021,9916001,9905007,9923001
3,01JAN2020:02:19:55,111612319,71122461,317361,EPINEPHrine 0.1 MG/ML ...,1.0,3706021,9916001,9905007,9923001
4,01JAN2020:02:24:55,111612320,71122461,317361,EPINEPHrine 0.1 MG/ML ...,1.0,3706021,9916001,9905007,9923001
...,...,...,...,...,...,...,...,...,...,...
1544323,Not Recorded,203434138,131775485,7701003,Not Recorded ...,0.0,7701003,7701003,7701003,7701003
1544324,Not Recorded,203473576,131801464,7701003,Not Recorded ...,0.0,7701003,7701003,7701003,7701003
1544325,Not Recorded,203473712,131801585,7701003,Not Recorded ...,0.0,7701003,7701003,7701003,7701003
1544326,Not Recorded,203473758,131801624,7701003,Not Recorded ...,0.0,7701003,7701003,7701003,7701003
1544327,Not Recorded,203473964,131801811,7701003,Not Recorded ...,0.0,7701003,7701003,7701003,7701003

In [3]:
selected_med_cols = ["PcrKey", "eMedications_03", "eMedications_03Descr"]

med_df = df[selected_med_cols]
hf.convert_type_to_int(med_df, ["eMedications_03"])
med_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1544328 entries, 0 to 1544327
Data columns (total 3 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   PcrKey                1544328 non-null  int64
 1   eMedications_03       1544158 non-null  Int64
 2   eMedications_03Descr  1544328 non-null  object
dtypes: Int64(1), int64(1), object(1)
memory usage: 36.8+ MB

/home/ng.chu/nemsis_project/helper_functions.py:157: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[series_name] = pd.to_numeric(df[series_name], errors='coerce').astype('Int64', errors='ignore')

In [4]:
med_df.shape[0]
# med_df.head()

1544328

In [5]:
# Drop answers of "Not Applicable" and "Not Recorded"
filtered_med_df = med_df[~((med_df.eMedications_03 == 7701001) | (med_df.eMedications_03 == 7701003))]

In [6]:
# Check the amount of recorded Pertinent Negatives (PN)
filtered_med_df[filtered_med_df["eMedications_03"].isin([8801001,8801003,8801007,8801009,8801019,8801023,8801027])].shape[0]

49

In [7]:
filtered_med_df[:]

,PcrKey,eMedications_03,eMedications_03Descr
0,71122461,317361,EPINEPHrine 0.1 MG/ML ...
1,71122461,317361,EPINEPHrine 0.1 MG/ML ...
2,71122461,317361,EPINEPHrine 0.1 MG/ML ...
3,71122461,317361,EPINEPHrine 0.1 MG/ML ...
4,71122461,317361,EPINEPHrine 0.1 MG/ML ...
...,...,...,...
1536457,121384546,8801001,Not Applicable ...
1538226,122320784,8801001,Not Applicable ...
1539210,122842002,8801001,Not Applicable ...
1539706,123095806,8801003,Contraindication Noted ...
1541717,126595692,8801001,Not Applicable ...

In [8]:
def create_simple_one_hot_col(df, col, new_col, value_lists):
    """
    function: turn certain values in an existing column into a new one-hot-encoded column.
    return: nothing, modify the passed-in DataFrame in-place.
    """
    df[new_col] = df[col].isin(value_lists).astype(int)

In [9]:
# Step 1: Identify if Epinephrine was used
create_simple_one_hot_col(df = filtered_med_df, 
                          col = 'eMedications_03', 
                          new_col = 'EpinephrineUsed', 
                          value_lists = [317361, 328316])

/tmp/ipykernel_1704/862293327.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col] = df[col].isin(value_lists).astype(int)

In [10]:
# Review the newly created column of EpinephrineUsed
filtered_med_df[:]

,PcrKey,eMedications_03,eMedications_03Descr,EpinephrineUsed
0,71122461,317361,EPINEPHrine 0.1 MG/ML ...,1
1,71122461,317361,EPINEPHrine 0.1 MG/ML ...,1
2,71122461,317361,EPINEPHrine 0.1 MG/ML ...,1
3,71122461,317361,EPINEPHrine 0.1 MG/ML ...,1
4,71122461,317361,EPINEPHrine 0.1 MG/ML ...,1
...,...,...,...,...
1536457,121384546,8801001,Not Applicable ...,0
1538226,122320784,8801001,Not Applicable ...,0
1539210,122842002,8801001,Not Applicable ...,0
1539706,123095806,8801003,Contraindication Noted ...,0
1541717,126595692,8801001,Not Applicable ...,0

In [11]:
# locate the row indexes of selected values
def loc_row_indexes_in_single_col(df, col, value_lists):
    """
    function: locate the row indexes of selected values
    return: a list of Bool, indicating if the value exists
    """
    return df[col].isin(value_lists)

# Step 1: Identify rows where Epinephrine was used
mask = loc_row_indexes_in_single_col(filtered_med_df, 'eMedications_03', [317361, 328316])
mask[:]

0           True
1           True
2           True
3           True
4           True
           ...
1536457    False
1538226    False
1539210    False
1539706    False
1541717    False
Name: eMedications_03, Length: 1359847, dtype: boolean

In [12]:
# Create a new column in the df to map the value based on an existing column
def map_values_to_new_col(df, index_mask, col, new_col, value_map):
    """
    function: Create a new column in the df to map the value based on an existing column
    return: nothing, new column added in-place
    """
    df.loc[index_mask, new_col] = df.loc[index_mask, col].map(value_map)
    df[new_col].fillna(0, inplace=True) # fill NaN with 0 <- not in map, no Epinephrine used

In [13]:
# Step 2: Calculate the dosage based on the code
map_values_to_new_col(df = filtered_med_df,
                      index_mask = mask,
                      col = 'eMedications_03',
                      new_col = 'EpinephrineDosage',
                      value_map = {317361: 0.1, 328316: 1})

filtered_med_df[:]

/tmp/ipykernel_1704/3771706423.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[index_mask, new_col] = df.loc[index_mask, col].map(value_map)
/tmp/ipykernel_1704/3771706423.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[new_col].fillna(0, inplace=True) # fill NaN with 0 <- not in map, no Epinephrine used

,PcrKey,eMedications_03,eMedications_03Descr,EpinephrineUsed,EpinephrineDosage
0,71122461,317361,EPINEPHrine 0.1 MG/ML ...,1,0.1
1,71122461,317361,EPINEPHrine 0.1 MG/ML ...,1,0.1
2,71122461,317361,EPINEPHrine 0.1 MG/ML ...,1,0.1
3,71122461,317361,EPINEPHrine 0.1 MG/ML ...,1,0.1
4,71122461,317361,EPINEPHrine 0.1 MG/ML ...,1,0.1
...,...,...,...,...,...
1536457,121384546,8801001,Not Applicable ...,0,0.0
1538226,122320784,8801001,Not Applicable ...,0,0.0
1539210,122842002,8801001,Not Applicable ...,0,0.0
1539706,123095806,8801003,Contraindication Noted ...,0,0.0
1541717,126595692,8801001,Not Applicable ...,0,0.0

In [14]:
# Calculate the total amount of Epinephrine
def calculate_sum_group_by_pcr_key(df, key, col, new_col):
    """
    function: Calculate the Epinephrine Dosage Total Amount, 
            put them in a new column grouped by primary key
    return: new DataFrame with the new column showing the total amount
    """
    new_df = df.groupby(key)[col].sum().reset_index()
    new_df.rename(columns = {col : new_col}, inplace=True)
    return new_df

In [15]:
# Step 3a: Calculate the frequency of Epinephrine used for each PcrKey -> group by PcrKey
frequency_med_df = calculate_sum_group_by_pcr_key(filtered_med_df, 'PcrKey', 'EpinephrineUsed', 'EpinephrineFrequency')
frequency_med_df

           PcrKey  EpinephrineFrequency
0        71122461                     6
1        71122902                     8
2        71145732                     0
3        71146549                     2
4        71147389                     0
...           ...                   ...
263729  131667017                     0
263730  131667110                     8
263731  131801015                     0
263732  131801460                     0
263733  131801707                     0

[263734 rows x 2 columns]

In [16]:
# Step 3b: Calculate the total amount of Epinephrine used for each PcrKey -> group by PcrKey
total_dosage_med_df = calculate_sum_group_by_pcr_key(filtered_med_df, 'PcrKey', 'EpinephrineDosage', 'EpinephrineTotalAmount')
total_dosage_med_df.head()

     PcrKey  EpinephrineTotalAmount
0  71122461                     0.6
1  71122902                     0.8
2  71145732                     0.0
3  71146549                     0.2
4  71147389                     0.0

In [17]:
# Only keep one row of each duplicated PcrKey after calculating Epinephrine amount
# [!!] XOR operation on the EpinephrineUsed column [!!]
filtered_med_df2 = filtered_med_df.drop(columns=["eMedications_03", "eMedications_03Descr", "EpinephrineDosage"])  # Drop prev used columns

# Aggregate 'EpinephrineUsed' column using logical OR (any '1' remains '1')
agg_functions = {'EpinephrineUsed': 'max'}
# Apply aggregation and then drop duplicates
med_df_unique = filtered_med_df2.groupby('PcrKey').agg(agg_functions).reset_index()

med_df_unique[:]

           PcrKey  EpinephrineUsed
0        71122461                1
1        71122902                1
2        71145732                0
3        71146549                1
4        71147389                0
...           ...              ...
263729  131667017                0
263730  131667110                1
263731  131801015                0
263732  131801460                0
263733  131801707                0

[263734 rows x 2 columns]

In [18]:
# Step 4a: Merge the frequency back to the original dataframe
grouped_med_df1 = pd.merge(med_df_unique, frequency_med_df, on='PcrKey', how='left')

In [19]:
# Step 4b: Merge the total dosage back to the original dataframe
grouped_med_df2 = pd.merge(grouped_med_df1, total_dosage_med_df, on='PcrKey', how='left')

In [20]:
grouped_med_df2[:]

,PcrKey,EpinephrineUsed,EpinephrineFrequency,EpinephrineTotalAmount
0,71122461,1,6,0.6
1,71122902,1,8,0.8
2,71145732,0,0,0.0
3,71146549,1,2,0.2
4,71147389,0,0,0.0
...,...,...,...,...
263729,131667017,0,0,0.0
263730,131667110,1,8,0.8
263731,131801015,0,0,0.0
263732,131801460,0,0,0.0
263733,131801707,0,0,0.0

In [21]:
grouped_med_df2.shape[0]

263734

In [22]:
# Round the 'EpinephrineTotalAmount' column to 2 decimal places to prevent float discrepancies
grouped_med_df2['EpinephrineTotalAmount'] = grouped_med_df2['EpinephrineTotalAmount'].round(2)
grouped_med_df2

,PcrKey,EpinephrineUsed,EpinephrineFrequency,EpinephrineTotalAmount
0,71122461,1,6,0.6
1,71122902,1,8,0.8
2,71145732,0,0,0.0
3,71146549,1,2,0.2
4,71147389,0,0,0.0
...,...,...,...,...
263729,131667017,0,0,0.0
263730,131667110,1,8,0.8
263731,131801015,0,0,0.0
263732,131801460,0,0,0.0
263733,131801707,0,0,0.0

In [23]:
grouped_med_df2.to_csv('clustering_data/epinephrine_cols.csv', index=False)